convnext_tiny:
  model: "torchvision.models.convnext_tiny"
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 10


convnext_small:
  model: "torchvision.models.convnext_small"
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 10


convnext_base:
  model: "torchvision.models.base"
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 10